### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by NaJeehye** [kaist-dmlab/DF-TAR#2]
There are only application examples about Korea, 
but will there be meaningful results if I apply this to data from other countries?

**Comment by itouchz** [comment]
Yes, we also expect the meaningful results from other countries as there are other datasets related to traffic accidents such as New York City and Beijing you may try. However, these datasets do not include (dangerous) driving behavior usually due to privacy issues. Therefore, if you would like to use our model for other datasets, please request relevant datasets from the respective authority in those contries. Thank you!
